[workspace]
members = ["ebpf-sniffer", "ebpf-sniffer-ebpf"]
resolver = "2"

[workspace.dependencies]
aya = { version = "0.12" }
aya-log = "0.2"

[patch.crates-io]
aya-log-common = "=0.1.15"

[profile.release]
lto = true
opt-level = 3
